### ISSUE TITLE
Installation error.

### ISSUE THREAD

**Issue by jernst** [uboslinux/ubos-wordpress#12]
```
ERROR: Initializing Wordpress failed: PHP Fatal error:  Uncaught phpmailerException: Invalid address: wordpress@-not-assigned-yet in /srv/http/sites/s370e23f7f2a6ebfec063456ace952a0836bed32d/blog/wp-includes/class-phpmailer.php:946
Stack trace:
#0 /srv/http/sites/s370e23f7f2a6ebfec063456ace952a0836bed32d/blog/wp-includes/pluggable.php(352): PHPMailer->setFrom('wordpress@-not-...', 'WordPress', false)
#1 /srv/http/sites/s370e23f7f2a6ebfec063456ace952a0836bed32d/blog/wp-admin/includes/upgrade.php(392): wp_mail('test@ubos.net', 'New WordPress S...', 'Your new WordPr...')
#2 /srv/http/sites/s370e23f7f2a6ebfec063456ace952a0836bed32d/blog/wp-admin/includes/upgrade.php(95): wp_new_blog_notification('My Wordpress Bl...', 'http://-not-ass...', 1, 'The password yo...')
#3 /srv/http/sites/s370e23f7f2a6ebfec063456ace952a0836bed32d/blog/wp-admin/install.php(367): wp_install('My Wordpress Bl...', 'admin', 'test@ubos.net', 1, '', 'qwerqwer', 'en_US')
#4 -(16): require_once('/srv/http/sites...')
#5 {main}
  thrown in /srv/http/sites/s370e23f7f2a6ebfec063456ace952a0836bed32d/blog/wp-includes/class-phpmailer.php on line 946
```

**Comment by jernst** [comment]
Cannot reproduce.
